export const ANCIENT_SCRIPTS = {
  CHAOS: [
    { char: "𓀀", meaning: "人 (古埃及)" },
    { char: "𓀀", meaning: "人 (古埃及)" },
    { char: "𒀀", meaning: "水 (楔形文字)" },
    { char: "𒀀", meaning: "水 (楔形文字)" },
    { char: "人", meaning: "人 (隶书)" },
    { char: "𓀁", meaning: "祈祷 (古埃及)" },
    { char: "𓀁", meaning: "祈祷 (古埃及)" },
    { char: "𒀁", meaning: "丰饶 (楔形文字)" },
    { char: "𒀁", meaning: "丰饶 (楔形文字)" },
    { char: "女", meaning: "女 (隶书)" },
    { char: "𓀂", meaning: "鞠躬 (古埃及)" },
    { char: "𓀂", meaning: "鞠躬 (古埃及)" },
    { char: "𒇽", meaning: "人 (楔形文字)" },
    { char: "𒇽", meaning: "人 (楔形文字)" },
    { char: "𒊩", meaning: "女 (楔形文字)" },
    { char: "𒊩", meaning: "女 (楔形文字)" },
    { char: "龍", meaning: "龙 (隶书)" },
    { char: "𓃠", meaning: "猫 (古埃及)" },
    { char: "𒂼", meaning: "母亲 (楔形文字)" }
  ],
  SACRED: [
    { char: "𓇳", meaning: "太阳 (古埃及)" },
    { char: "𓇳", meaning: "太阳 (古埃及)" },
    { char: "𓊹", meaning: "神灵 (古埃及)" },
    { char: "𓊹", meaning: "神灵 (古埃及)" },
    { char: "𒀭", meaning: "神/天 (楔形文字)" },
    { char: "𒀭", meaning: "神/天 (楔形文字)" },
    { char: "日", meaning: "日 (隶书)" },
    { char: "𓇼", meaning: "星 (古埃及)" },
    { char: "𓇼", meaning: "星 (古埃及)" },
    { char: "𒌓", meaning: "日/光 (楔形文字)" },
    { char: "𒌓", meaning: "日/光 (楔形文字)" },
    { char: "天", meaning: "天 (隶书)" },
    { char: "神", meaning: "神 (隶书)" },
    { char: "星", meaning: "星 (隶书)" },
    { char: "𓆣", meaning: "圣甲虫 (古埃及)" },
    { char: "𒂍", meaning: "神庙 (楔形文字)" }
  ],
  LIFE: [
    { char: "𓋹", meaning: "生命 (古埃及)" },
    { char: "𓋹", meaning: "生命 (古埃及)" },
    { char: "𓈗", meaning: "水 (古埃及)" },
    { char: "𓈗", meaning: "水 (古埃及)" },
    { char: "𒀀", meaning: "水 (楔形文字)" },
    { char: "𒀀", meaning: "水 (楔形文字)" },
    { char: "𓎛", meaning: "莲花 (古埃及)" },
    { char: "𓎛", meaning: "莲花 (古埃及)" },
    { char: "水", meaning: "水 (隶书)" },
    { char: "雨", meaning: "雨 (隶书)" },
    { char: "木", meaning: "木 (隶书)" },
    { char: "生", meaning: "生 (隶书)" },
    { char: "山", meaning: "山 (隶书)" },
    { char: "𓆭", meaning: "树 (古埃及)" },
    { char: "𓆰", meaning: "草木 (古埃及)" },
    { char: "𒌉", meaning: "孩子 (楔形文字)" }
  ],
  POWER: [
    { char: "𓂡", meaning: "力量 (古埃及)" },
    { char: "𓂡", meaning: "力量 (古埃及)" },
    { char: "𓌀", meaning: "权杖 (古埃及)" },
    { char: "𓌀", meaning: "权杖 (古埃及)" },
    { char: "𒈗", meaning: "王 (楔形文字)" },
    { char: "𒈗", meaning: "王 (楔形文字)" },
    { char: "火", meaning: "火 (隶书)" },
    { char: "炎", meaning: "炎 (隶书)" },
    { char: "雷", meaning: "雷 (隶书)" },
    { char: "力", meaning: "力 (隶书)" },
    { char: "戈", meaning: "戈 (隶书)" },
    { char: "𓄿", meaning: "鹰 (古埃及)" },
    { char: "𓂢", meaning: "强力 (古埃及)" },
    { char: "𓌔", meaning: "弓 (古埃及)" }
  ],
  PEACE: [
    { char: "𓆄", meaning: "真理 (古埃及)" },
    { char: "𓆄", meaning: "真理 (古埃及)" },
    { char: "𓅂", meaning: "灵魂 (古埃及)" },
    { char: "𓅂", meaning: "灵魂 (古埃及)" },
    { char: "𒆠", meaning: "地 (楔形文字)" },
    { char: "𒆠", meaning: "地 (楔形文字)" },
    { char: "和", meaning: "和 (隶书)" },
    { char: "平", meaning: "平 (隶书)" },
    { char: "安", meaning: "安 (隶书)" },
    { char: "合", meaning: "合 (隶书)" },
    { char: "𓅛", meaning: "燕子 (古埃及)" }
  ],
  CREATION: [
    { char: "𓁶", meaning: "创造 (古埃及)" },
    { char: "𓁶", meaning: "创造 (古埃及)" },
    { char: "𓋹", meaning: "生命 (古埃及)" },
    { char: "𓋹", meaning: "生命 (古埃及)" },
    { char: "𓂡", meaning: "力量 (古埃及)" },
    { char: "𓂡", meaning: "力量 (古埃及)" },
    { char: "𒂍", meaning: "殿/屋 (楔形文字)" },
    { char: "𒂍", meaning: "殿/屋 (楔形文字)" },
    { char: "造", meaning: "造 (隶书)" },
    { char: "化", meaning: "化 (隶书)" },
    { char: "源", meaning: "源 (隶书)" },
    { char: "始", meaning: "始 (隶书)" }
  ],
  WISDOM: [
    { char: "𓏞", meaning: "智慧 (古埃及)" },
    { char: "𓏞", meaning: "智慧 (古埃及)" },
    { char: "𓁻", meaning: "视觉 (古埃及)" },
    { char: "𓁻", meaning: "视觉 (古埃及)" },
    { char: "𒋗", meaning: "手 (楔形文字)" },
    { char: "𒋗", meaning: "手 (楔形文字)" },
    { char: "智", meaning: "智 (隶书)" },
    { char: "慧", meaning: "慧 (隶书)" },
    { char: "学", meaning: "学 (隶书)" },
    { char: "思", meaning: "思 (隶书)" },
    { char: "𓓏", meaning: "卷轴 (古埃及)" }
  ],
  ORACLE: [
    { char: "日", meaning: "日 (甲骨文)" },
    { char: "月", meaning: "月 (甲骨文)" },
    { char: "山", meaning: "山 (甲骨文)" },
    { char: "水", meaning: "水 (甲骨文)" },
    { char: "目", meaning: "目 (甲骨文)" },
    { char: "人", meaning: "人 (甲骨文)" },
    { char: "龟", meaning: "龟 (甲骨文)" },
    { char: "卜", meaning: "卜 (甲骨文)" },
    { char: "𓇯", meaning: "天空 (古埃及)" },
    { char: "𓇿", meaning: "大地 (古埃及)" },
    { char: "𓏴", meaning: "征兆 (古埃及)" },
    { char: "𓁻", meaning: "启示 (古埃及)" },
    { char: "𓊹", meaning: "神谕 (古埃及)" },
    { char: "𒉆", meaning: "命运 (楔形文字)" },
    { char: "𒈨", meaning: "神力 (楔形文字)" },
    { char: "𒄬", meaning: "占卜 (楔形文字)" },
    { char: "𒀭", meaning: "天启 (楔形文字)" }
  ],
  CONFLICT: [
    { char: "𓌙", meaning: "投掷 (古埃及)" },
    { char: "𓌙", meaning: "投掷 (古埃及)" },
    { char: "𓌗", meaning: "鱼叉 (古埃及)" },
    { char: "𓌗", meaning: "鱼叉 (古埃及)" },
    { char: "𒆳", meaning: "山/敌国 (楔形文字)" },
    { char: "𒆳", meaning: "山/敌国 (楔形文字)" },
    { char: "战", meaning: "战 (隶书)" },
    { char: "争", meaning: "争 (隶书)" },
    { char: "乱", meaning: "乱 (隶书)" },
    { char: "戈", meaning: "戈 (隶书)" }
  ],
  HARMONY: [
    { char: "𓊽", meaning: "稳定 (古埃及)" },
    { char: "𓊽", meaning: "稳定 (古埃及)" },
    { char: "𓂧", meaning: "奉献 (古埃及)" },
    { char: "𓂧", meaning: "奉献 (古埃及)" },
    { char: "𒃻", meaning: "食物 (楔形文字)" },
    { char: "𒃻", meaning: "食物 (楔形文字)" },
    { char: "和", meaning: "和 (隶书)" },
    { char: "平", meaning: "平 (隶书)" },
    { char: "合", meaning: "合 (隶书)" },
    { char: "圆", meaning: "圆 (隶书)" }
  ]
};

export type Theme = keyof typeof ANCIENT_SCRIPTS;
export type ScriptItem = { char: string; meaning: string };

export const GESTURE_MAP: Record<string, Theme> = {
  "PRAYER": "SACRED",
  "OPEN_PALM": "LIFE",
  "FIST": "WISDOM",
  "PEACE": "PEACE",
  "THUMBS_UP": "POWER",
  "INDEX_POINTING": "ORACLE",
  "DUAL_PEACE": "HARMONY",
  "POWER_LIFE": "CREATION",
  "LIFE_POWER": "CONFLICT",
  "NONE": "CHAOS"
};
